travis:
  secure:
    BINSTAR_TOKEN: tuJyGD8+jfvCq68Fi1pa0d3EBxuX96aBHyjZcB7oJxCSDsuop+VBiMxhBPqzQC3g+Ij9ogEyKKsWgijiNmRvP1OEocCJScH6CjqF+I6q62uO3zhStUW+xBHx1stbipbU0hdMqWx0O+lf1dphrF/6XX7DAy/uxREOZLvv38Sby0S2VRfmb3MKHuQxkwKqYZyk4VAInhh1oPhzYPjra1Iuft8fGnaSxjOQBv+diCShlTITSd7NM830Rtkn96xOq+z0QAdep79NRr3/RUQRJTzZlHmJBuHhEO/03HC+s4SFDwezq+8CPIBTdfF6M/ixE0ZuRMeWvfOuAsHRUWWxHr/CVRiQY2QzGdvzK+NEVzVkfw897TRjsGMq3DGdeUuRNAguSDwo0zeyZDfBEW1EyY0BebdfYKsocNHHDpdCrsfnqZSVqZCdvUXvGnN2R6MWjo/HK4PfneH2+f9Gr6TYYTfI9Rpu/s6fQ6bcsNROpGEP3IcoiKVJsbMtmMlFFwkZS+xjN0721fpesJxBhuWfY6Pe0oMDFxT4ard209PFdhC4TwLeNfEVWq9ncn1/NP0RgzTEl8KELyW4eqpXhG1bNVQAFW0z6KjRAsaM4ejStSChwsJte7MSv4UF2MBxy0JETbVyfvtIBfV+FfXeySx187hlcWP+DEE2vMnrKVt/irA3uGM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
