travis:
  secure:
    BINSTAR_TOKEN: 0mF7YkNKJMJcUzyR+2ejZM48LFF8B2dP7Zlrmu0ZcNAO7YKO9kP5dkpOMcA6PdG3dqhwz69RjNnm3pvc6sxiiXn2e5je7e2r6l3Gll2p5TifH0ljbT9Lpw8gowR6XFB4jFizgqtuzIbMwOxz8glX98gAqnewTjT80jVguswaMdrY3C9tjEA5z6iZXpFS3DzYHYlFqFNeFPhLq0sdWTBV/WWWhkTFq/nHeMPPsdmSCyrSp0ngcI740cv6G8ch3sQ7+3A4J5Sk7Fh5vSpOS2Mx9sa7/tfSKruDiWtkEfYsw0EQwCIVTqZWtsVWDoBTMVnE92slFaRlYMvPLOxYqAqm9tdIfDoA2HQjkwY5/IcJaXgM6I8ubRG/iL0+NnbI5WDhmvskILp3f9x8w1XjkH3QGZ6VP5Pzq1/EZxbIdGFWwPPXMpsCls3ujnLcJ8tb4bqBTfoXjiKwwsXxIkyYrD3/J9RAwcptGEnU682KiXUoZUCZJB1TfWSlmKaBNWxfmrd8hiY1Zjl5PG2sDW9+REqChLiIRGsl0s69DabAu7clADmNzor27vZpFkuEDubKyOGOOxli3hRk5R91mC07fI1TMrV5vVc4bW5NwTQ6PBaCWy5b9nzP49SPJtdkKVhUnPgZKsNVVipoHx9mnxjA6dchHYHWVbN829xXzrVzbBuaUHE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
